<?php

use App\Http\Controllers\employerController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ReportsController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\JobListingController;
use App\Http\Controllers\JobSeekerController;
use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\FavoriteJobController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ProfileController;

Route::get('/user', function (Request $request) {
    return $request->user();
})->middleware('auth:sanctum');

Route::middleware('auth:sanctum')->group(function () {
    Route::get('/user/cv', [ApplicationController::class, 'getUserCV']);
    Route::post('/applications/submit', [ApplicationController::class, 'submit']);
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::get('/profile', [AuthController::class, 'userProfile']);
    Route::get('/job-seeker', [JobSeekerController::class, 'getProfile']);
    Route::post('/job-seeker/upload-resume', [JobSeekerController::class, 'uploadResume']);
    Route::get('/applications/by-job-seeker/{jobSeekerId}', [ApplicationController::class, 'getApplicationsByJobSeekerId']);
    Route::get('/employer', [JobListingController::class, 'getEmployerByUser']);
    Route::get('/user/profile', [ProfileController::class, 'getProfile']);
    Route::post('/user/profile', [ProfileController::class, 'updateProfile']);
    Route::put('/seeker/profile/basic', [ProfileController::class, 'updateBasicInfo']);
    Route::put('/seeker/profile/resume', [ProfileController::class, 'updateResumeInfo']);
    Route::post('/user/profile/picture', [ProfileController::class, 'uploadProfilePicture']);
    Route::post('/user/resume', [ProfileController::class, 'uploadResume']);
    Route::get('/job-seekers/{id}', [ProfileController::class, 'getJobSeekerProfile']);
    Route::get('/job-seekers/{id}/resume', [ProfileController::class, 'downloadResume']);
    Route::post('/user/update-password', [ProfileController::class, 'updatePassword']);
    Route::get('/favorite-jobs', [FavoriteJobController::class, 'index']);
    Route::post('/favorite-jobs', [FavoriteJobController::class, 'store']);
    Route::delete('/favorite-jobs/{jobId}', [FavoriteJobController::class, 'destroy']);

    Route::put('/employer/profile', [EmployerController::class, 'update']);
    Route::put('/employer/profile', [EmployerController::class, 'show']);
});

Route::get('/roles', [AuthController::class, 'getRoles']);
Route::post('/register', [AuthController::class, 'register']);
Route::post('/verify-code', [AuthController::class, 'verifyCode']);
Route::post('/login', [AuthController::class, 'login']);
Route::post('/forgot-password', [AuthController::class, 'forgotPassword']);
Route::post('/verify-forgot-code', [AuthController::class, 'verifyForgotCode']);
Route::post('/reset-password', [AuthController::class, 'resetPassword']);
Route::get('/applications', [ApplicationController::class, 'index']);
Route::get('/applications/{id}', [ApplicationController::class, 'show']);
Route::post('/applications', [ApplicationController::class, 'store']);
Route::put('/applications/{id}', [ApplicationController::class, 'update']);
Route::delete('/applications/{id}', [ApplicationController::class, 'destroy']);
Route::put('/categories/{id}', [CategoryController::class, 'update']);
Route::delete('/categories/{id}', [CategoryController::class, 'destroy']);
Route::get('/categories/{id}', [CategoryController::class, 'show']);
Route::get('/categories', [CategoryController::class, 'index']);
Route::post('/categories', [CategoryController::class, 'store']);
Route::get('/jobs', [JobListingController::class, 'getAll']);
Route::get('/jobs/{id}', [JobListingController::class, 'getById']);
Route::middleware('auth:sanctum')->get('/employer', [JobListingController::class, 'getEmployerByUser']);
Route::middleware('auth:sanctum')->group(function () {
    Route::get('/employer/{employerId}/jobs', [JobListingController::class, 'getByEmployer']);
    Route::post('/jobs', [JobListingController::class, 'create']);
    Route::put('/jobs/{id}', [JobListingController::class, 'update']);
    Route::put('/jobs/{id}/status', [JobListingController::class, 'updateStatus']);
    Route::delete('/jobs/{id}', [JobListingController::class, 'delete']);
    Route::get('/notifications', [NotificationController::class, 'index']);
    Route::get('/notifications/unread', [NotificationController::class, 'unread']);
    Route::post('/notifications/mark-as-read/{id}', [NotificationController::class, 'markAsRead']);
    Route::post('/notifications/seeker/{seekerId}/{status}', [NotificationController::class, 'notifySeekerApplicationStatus']);
    Route::post('/notifications/employer/{employerId}/{type}', [NotificationController::class, 'notifyEmployerActivity']);
    Route::get('/reports/employer-stats/{id}', [ReportsController::class, 'getEmployerStats']);
    Route::get('/reports/employer-Line-chart/{id}', [ReportsController::class, 'getEmployerLineChartData']);
    Route::post('/applications/upload-cv-and-cover-letter', [ApplicationController::class, 'uploadCVAndCoverLetter']);
    //Route::get('/jobs/recommended', [JobListingController::class, 'getRecommendedJobs']);
    Route::get('/jobs/recommended', [JobListingController::class, 'getRecommendedJobsForSeeker']);
});

Route::middleware(['auth:sanctum', 'admin'])->group(function () {
    Route::get('/admin/users', [AdminController::class, 'allUsers']);
    Route::post('/admin/users', [AdminController::class, 'addUser']);
    Route::put('/admin/users/{id}', [AdminController::class, 'updateUser']);
    Route::delete('/admin/users/{id}', [AdminController::class, 'deleteUser']);
    Route::get('admin/employers/pending', [AdminController::class, 'pendingEmployerRequests']);
    Route::post('admin/employers/{id}/approve', [AdminController::class, 'approveEmployer']);
    Route::post('admin/employers/{id}/reject', [AdminController::class, 'rejectEmployer']);
    Route::get('/admin/job-stats', [AdminController::class, 'jobDemandStats']);
    Route::get('/admin/job-listings', [AdminController::class, 'allJobListings']);
    Route::delete('/admin/job-listings/{id}', [AdminController::class, 'deleteJobListing']);
    Route::get('/admin/user-count', [AdminController::class, 'userCount']);
    Route::get('/admin/employer-count', [AdminController::class, 'employerCount']);
    Route::get('/admin/job-seeker-count', [AdminController::class, 'jobSeekerCount']);
    Route::get('/admin/job-listing-count', [AdminController::class, 'jobListingCount']);
    Route::get('/admin/accepted-applications', [AdminController::class, 'acceptedApplicationsCount']);
    Route::get('/admin/rejected-applications', [AdminController::class, 'rejectedApplicationsCount']);
    Route::get('/admin/latest-jobs', [AdminController::class, 'latestJobListings']);
    Route::get('/admin/job-overview-table', [AdminController::class, 'jobOverviewTable']);
    Route::get('/admin/applications-stats', [AdminController::class, 'getApplicationsStats']);
});
Route::get('/search-jobs', [JobListingController::class, 'advancedSearch']);
Route::get('/jobs/category/{category}', [JobListingController::class, 'getJobsByCategory']);
Route::post('/reset-password', [AuthController::class, 'resetPassword']);
Route::get('/applications', [ApplicationController::class, 'index']);
Route::get('/applications/{id}', [ApplicationController::class, 'show']);
Route::post('/applications', [ApplicationController::class, 'store']);
Route::put('/applications/{id}', [ApplicationController::class, 'update']);
Route::delete('/applications/{id}', [ApplicationController::class, 'destroy']);
Route::get('/applications/job/{jobId}', [ApplicationController::class, 'getApplicantsByJobId']);
Route::get('/applications/detail/{id}', [ApplicationController::class, 'getApplicationById']);
Route::get('/categories', [CategoryController::class, 'index']);
Route::get('/categories/{id}', [CategoryController::class, 'show']);
Route::post('/categories', [CategoryController::class, 'store']);
Route::put('/categories/{id}', [CategoryController::class, 'update']);
Route::delete('/categories/{id}', [CategoryController::class, 'destroy']);
Route::get('/favorites', [FavoriteJobController::class, 'index']);
Route::post('/favorites', [FavoriteJobController::class, 'store']);
Route::delete('/favorites/{id}', [FavoriteJobController::class, 'destroy']);
Route::get('/favorites/job-seeker/{jobSeekerId}', [FavoriteJobController::class, 'getByJobSeeker']);
Route::get('/jobs', [JobListingController::class, 'getAll']);
Route::get('/jobs/{id}', [JobListingController::class, 'getById']);
Route::get('/job-form-options', [JobListingController::class, 'getJobFormOptions']);
Route::get('/user', function (Request $request) {
    return $request->user();
})->middleware('auth:sanctum');
Route::get('/reports/admin-stats', [ReportsController::class, 'getAdminStats']);
Route::get('/reports/admin-bar-chart', [ReportsController::class, 'getAdminBarchartData']);
